services:
  site:
    image: henriquedandrade/sentinela:node-app
    ports:
      - "3333:3333"
    networks:
      - rede-compose
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: senha123
      DB_DATABASE: sentinela
    
  db:
    image: henriquedandrade/sentinela:mysql-app
    ports:
      - "3307:3306"
    networks:
      - rede-compose
    
networks:
  rede-compose:
    driver: bridge

